### ISSUE TITLE
Fast charging

### ISSUE THREAD

**Issue by imrankadd** [WisniaPL/x500-device-tree#10]
It does not support fast charging... It takes around 1:45 to 2:15, which is quite long time as compare to Los13 which take only max 60 min to fully charge

**Comment by WisniaPL** [comment]
I know about this. Can you provide link to this rom?

**Comment by iamsdas** [comment]
Link - https://drive.google.com/file/d/0B74a3P9pFL6TckMtdGpEa2JaVkU/view?usp=drivesdk

**Comment by WisniaPL** [comment]
ok, thanks

**Comment by WisniaPL** [comment]
No fast charging in rom from your link..

**Comment by imrankadd** [comment]
You made this ROM so why are you asking for ROM link bro?

**Comment by WisniaPL** [comment]
Not this one...

**Comment by imrankadd** [comment]
And the link which Suryashankardas gives you that is wrong link. I am talking about RR 5.8.2 (7.1.1) which is made by you bro. 
https://drive.google.com/file/d/0B2OqNYnhHqY4TnBpN2p1RlVUOHc/view

**Comment by imrankadd** [comment]
Please bro add fast charging in your both ROMs Los 14 and RR 5.8.2

**Comment by imrankadd** [comment]
Los 13 support fast charging. I had tested that bro.

**Comment by iamsdas** [comment]
I gave  the link of Los 13 ROM the only one that exists for letting 1s. It can't be wrong.

**Comment by iamsdas** [comment]
Charging time is good in Los 14.1 so why need fast charge? It will cause heating issues while charging.

**Comment by pravinnirmal** [comment]
RR rom charging time is about 2.15 hrs. No fast charging.
