### ISSUE TITLE
Notification LED issue

### ISSUE THREAD

**Issue by pravinnirmal** [WisniaPL/x500-device-tree#11]
Notification LED sometimes doesnt glow sometimes glows all colours continuously when notification arrives.

**Comment by WisniaPL** [comment]
I think it could be changed by app. Unfortunetly in nougat there is no led changer like in marshmallow

**Comment by pravinnirmal** [comment]
I tried it but some colours are messing up like blue,green,red works good others colours are messing.

**Comment by WisniaPL** [comment]
And so it is better than the original ..

**Comment by pravinnirmal** [comment]
Yeah but if it works perfectly would love it anyway good work. And regarding today release can i install it over last build without wiping data or need to clean install?

**Comment by pravinnirmal** [comment]
Updated it thanks again. Front camera turning on hdr hangs camera.
