### ISSUE TITLE
Minor bugs in RR ROM

### ISSUE THREAD

**Issue by iamsdas** [WisniaPL/x500-device-tree#12]
While dragging the quick setting tiles from the bottom (while editing), the tile disappears. Eg - Android N Easter egg , ambient display etc.

For jio sim , it shows loop mobile ( this problem is there in almost all ROMs for letting 1s.) But it shows the normal jio 4g in Lineage OS 14.1 ROM.

**Comment by DarkAbhi** [comment]
He is not a Indian he has no idea about the loopmobile and jio issue

**Comment by WisniaPL** [comment]
You can try replace apn and spn files (system/etc)

**Comment by iamsdas** [comment]
What about the quick setting problem, can it be fixed by user side?
