### ISSUE TITLE
Live display

### ISSUE THREAD

**Issue by psycho-source** [WisniaPL/x500-device-tree#13]
The live display option in settings is not working! In previous Android version the manual RGB colour selector was of great use to stop the screen burn issue that is a big issue in these ROMs!

**Comment by DarkAbhi** [comment]
hey your back psycho

**Comment by psycho-source** [comment]
not exactly! got exams! but still trying to work!

**Comment by WisniaPL** [comment]
Live display fixed. I add in next builds.

**Comment by psycho-source** [comment]
awesome!!! finally no more screen burn!
