### ISSUE TITLE
Button configuration in lineage os

### ISSUE THREAD

**Issue by iamsdas** [WisniaPL/x500-device-tree#15]
In the latest lineage is (in which gesture support was added) the recent apps button doesn't work . It only opens search assistant on long press and menus for short press , tried changing the button actions from settings but did not work. Home button working perfectly, so currently using it instead recent apps button.

**Comment by SupaSaiyajinRoze** [comment]
System/usr/keylayout/synaptics_dsx_i2c.kl replace "MENU" with "APP_SWITCH" and do reboot.

**Comment by iamsdas** [comment]
The menu and recent apps button have not gotten switched,  just the recent apps button doesn't work properly. I just weekend the software keys from build. prop The software keys work properly.

**Comment by iamsdas** [comment]
So, did I do anything wrong during installation or is this a common problem?

**Comment by WisniaPL** [comment]
I changed keylayout in latest build. You can try flash this zip [https://www.androidfilehost.com/?fid=817550096634756270](url)
