### ISSUE TITLE
Snapchat doesn't login

### ISSUE THREAD

**Issue by DarkAbhi** [WisniaPL/x500-device-tree#16]
Just letting you know if you have a solution could you post here.

**Comment by psycho-source** [comment]
That's snapchat's security feature! you can bypass that! flash the stock ROM install and login your account in it! then usse titanium backup to backup and restore the snapchat! you will be logged in and won't have any problems afterwards!

**Comment by DarkAbhi** [comment]
Yeah I know did that , it logs you out .
You need to get back on telegram :p

**Comment by psycho-source** [comment]
okk ! coming back now! ;)
