### ISSUE TITLE
Wifi keeps disconnects and connects keep and keep going.

### ISSUE THREAD

**Issue by N1NaN0** [WisniaPL/x500-device-tree#20]
It's find when not using a internet but when internet connects some wifi keep disconnect then connect few seconds later then disconnect again  keep going this way. Please fix this bug.

**Comment by SscSPs** [comment]
Are you sure it's not because of some of your settings?
Because for others, it's fine..

**Comment by N1NaN0** [comment]
Yes I'm using it. I haven't touch anything yet. Especially my google fiber disconnects many times.
