### ISSUE TITLE
Need some help

### ISSUE THREAD

**Issue by springhack** [WisniaPL/x500-device-tree#21]
First thanks for this wonderful work.

I try build RR with device and vendor from your repos, kernel from another repo, and finally I flash it to my phone it stuck on bootloader screen (with a llittle brightness lower).

I got this in my .repo/local_manifest:

```
<?xml version="1.0" encoding="UTF-8"?>
<manifest>
  <project name="WisniaPL/x500-vendor-tree" path="vendor/LeTV/x500" remote="github" revision="LineageOS-14.1" />
  <project name="WisniaPL/x500-device-tree" path="device/LeTV/x500" remote="github" revision="LineageOS-14.1" />
  <project name="SuryashankarDas/android_kernel_LeTV_x500" path="kernel/LeTV/x500" remote="github" revision="master" />
</manifest>
```

I sync repos and follow the RR steps: 

```
. build/envsetup.sh
brunch x500
```

Anything help ?

Another thing, I am tring to fix CameraService (camera crash), but in current time we have a way just easy than reboot:

```
su -c pkill mediaserver
```

It's a tmp way simple to restart CameraService builtin MediaServer, if I can boot up my phone I may try to fix in right way.

**Comment by SscSPs** [comment]
This is because the kernel is not right. There are some issue with the making of boot.img
Try reverting the kernel repo by 2 commits(if you are on latest wisniapl's kernel tree)

**Comment by SscSPs** [comment]
And look into the arguments for boot.img.
Alternatively, you can flash the boot.img from latest RR by wisniapl over your build to boot

**Comment by springhack** [comment]
@SscSPs I will try later, thanks a lot !
