### ISSUE TITLE
YouTube

### ISSUE THREAD

**Issue by imrankadd** [WisniaPL/x500-device-tree#7]
YouTube freezing above 480p videos.
And VoLTE does not work

**Comment by imrankadd** [comment]
And Can't change LED notification color

**Comment by SscSPs** [comment]
Thanks for reporting

**Comment by SscSPs** [comment]
Thanks for reporting

**Comment by imrankadd** [comment]
Welcome sir, What you bro are doing that is awesome for us,,, thanks lot bro....

**Comment by SscSPs** [comment]
I am not doing anything as such as I don't know much, @WisniaPL is doing the real work.
It's all his work that we see here

**Comment by WisniaPL** [comment]
@imrankadd Youtube app or browser?

**Comment by imrankadd** [comment]
YouTube app bro.

**Comment by ZeNiX74** [comment]
Please fix camera bro. SOT of Los 14.1 is fine. But in the case of RR it is not satisfactory.

**Comment by ZeNiX74** [comment]
Can you add engineer mod on next build.

**Comment by ZeNiX74** [comment]
Root access is also required in order to use substratum. In RR substratum is working fine without SU.

**Comment by ZeNiX74** [comment]
Please fix 📷 . We are ready to make donation.

**Comment by ZeNiX74** [comment]
In YouTube app 1080p videos are playing without freezing.(LOS 14.1)

**Comment by imrankadd** [comment]
@WisniaPl  Hello sir, I found the reason of YouTube and other apps video freezing issue, and that is SuperSU, because without rooting YouTube was playing in 1080p without any issue but when rooted with SuperSU and again tried to play YouTube starts freezing even in 480p, So i request you that please enable root access inbuilt.
