### ISSUE TITLE
Video freezing

### ISSUE THREAD

**Issue by iamsdas** [WisniaPL/x500-device-tree#9]
Freezing in you tube app occurs always when playing 720p60 or 1080p60 videos. Also HD  videos (downloaded or recorded through camera of different ROMs )freez when playing through​ any average or pre installed media player (It only goes when using SW decoder of mx player or VLC media player).This bug is there in all the custom ROMs for le 1s Android 6.0+

**Comment by imrankadd** [comment]
@WisniaPL Hello sir, I found the reason of YouTube and other apps video freezing issue, and that is SuperSU, because without rooting YouTube was playing in 1080p without any issue but when rooted with SuperSU and again tried to play YouTube starts freezing even in 480p, So i request you that please enable root access inbuilt.

**Comment by iamsdas** [comment]
I had  installed the super su add on from official lineage OS. Not the normal super su. I think high frame rate videos freez. And like I said problem is also there in media player videos.

**Comment by iamsdas** [comment]
I think MOST PROBABLY this issue can be solved if some how MTK clear motion is enabled in this ROM.

**Comment by WisniaPL** [comment]
No clear motion on custom rom.

**Comment by iamsdas** [comment]
But clear motion was there in all custom ROMs for letting 1s based on Android 5.0.

**Comment by iamsdas** [comment]
I just hope this issue can be solved ( in any way ).

**Comment by WisniaPL** [comment]
Yes, only on android 5.0 for all mediatek devices but not for mm and nougat.

**Comment by iamsdas** [comment]
I noticed that not only the 60 fps videos freeze but also full HD videos below 60 fps .
